const express=require("express")
const app=express()
const jwt=require("jsonwebtoken")
const cors=require("cors")
const bodyParser=require("body-parser")
const multer=require('multer')
const storage = multer.diskStorage({
  destination: function (req, file, cb) {
    cb(null, './Uploads')
  },
  filename: function (req, file, cb) {
    const uniqueSuffix = Date.now() + '-' + Math.round(Math.random() * 1E9)
    cb(null,'-' + uniqueSuffix+ file.originalname)
  }
})
const upload = multer({ storage: storage })
const connect=require("./db")
const userModel=require("./models/users.Model")
const contactModel=require("./models/contact.Model")
const doctorModel=require("./models/doctor.model")
const patientmodel=require("./models/Patient.Model")
const appointmentmodel=require("./models/appointment.Model")
connect()
const loginRoutes=require("./Routes/Authentication")
const signRoute=require("./Routes/signRoute")
const contactRoute=require("./Routes/contactRoute")
const addDoctorRoute=require("./Routes/addDoctorRoute")
const doctorRoute=require("./Routes/doctorRoute")
const deleteDoctor=require("./Routes/deleteDoctor")
const updateDoctor=require("./Routes/updateDoctor")
const addPatient=require("./Routes/addPatientRoute")
const appointmentBooking=require("./Routes/appointmentBooking")
const allAppointments=require("./Routes/allAppointments")
const allPatients=require("./Routes/allPatients")
const singlePatientRoute=require("./Routes/Patient")
app.use(bodyParser.json())
app.use(cors())
app.use(express.static(__dirname+"/Public"))
app.use(express.json())
app.use("/login",loginRoutes)
app.use("/signUp",signRoute)
app.use("/contact",contactRoute)
app.use("/doctors",doctorRoute)
app.use("/patients",addPatient)
app.use("/addDoctor",addDoctorRoute)
app.use("/updateDoctor",updateDoctor)
app.use("/deleteDoctor",deleteDoctor)
app.use("/appointmentBooking",appointmentBooking)
app.use("/allAppointments",allAppointments)
app.use("/allPatients",allPatients)
app.use("/patient",singlePatientRoute)
app.get("/",(req,res)=>{
    res.send({msg:"Hello all"})
})
app.listen(3600,()=>{
    console.log("Server is running successfully")
})