const express=require("express")
const app=express()
const bodyParser=require("body-parser")
const connect=require("./db")
const userModel=require("./models/users.Model")
const contactModel=require("./models/contact.Model")
const {sign}=require("./Controllers/user.Controller")
const {login}=require("./Controllers/login.Controller")
const {contact}=require("./Controllers/contact.Controller")
connect()
app.use(bodyParser.json())
app.use(express.static(__dirname+"/Public"))
app.get("/",(req,res)=>{
    res.send({msg:"Hello all"})
})
app.post("/signUp",sign)
app.post("/login",login)
app.post("/contact",contact)
app.listen(3600,()=>{
    console.log("Server is running successfully")
})