const express=require("express")
const app=express()
const jwt=require("jsonwebtoken")
const cors=require("cors")
const bodyParser=require("body-parser")
const multer=require('multer')
const storage = multer.diskStorage({
  destination: function (req, file, cb) {
    cb(null, './Uploads')
  },
  filename: function (req, file, cb) {
    const uniqueSuffix = Date.now() + '-' + Math.round(Math.random() * 1E9)
    cb(null,'-' + uniqueSuffix+ file.originalname)
  }
})
const upload = multer({ storage: storage })
const connect=require("./db")
const userModel=require("./models/users.Model")
const contactModel=require("./models/contact.Model")
const doctorModel=require("./models/doctor.model")
const patientmodel=require("./models/Patient.Model")
const appointmentmodel=require("./models/appointment.Model")
const {sign}=require("./Controllers/user.Controller")
const {login}=require("./Controllers/login.Controller")
const {contact}=require("./Controllers/contact.Controller")
const {addDoctor,deleteDoctor,allDoctors,updateDoctor}=require("./Controllers/doctor.Controller")
const {appointments,allAppointments}=require("./Controllers/appointments.Controller")
const {patient,allPatients}=require("./Controllers/patient.Controllers")
connect()
app.use(bodyParser.json())
app.use(cors())
app.use(express.static(__dirname+"/Public"))
app.use(express.json())
app.get("/",(req,res)=>{
    res.send({msg:"Hello all"})
})
app.post("/signUp",sign)
app.post("/login",login)
app.post("/contact",contact)
app.post("/addDoctor",addDoctor)
app.get("/doctors",allDoctors)
app.delete("/deleteDoctor",deleteDoctor)
app.post("/patient",patient)
app.post("/appointmentBooking",appointments)
app.get("/allPatients",allPatients)
app.get("/allAppointments",allAppointments)
app.post("/updateDoctor",updateDoctor)
app.listen(3600,()=>{
    console.log("Server is running successfully")
})